
import java.util.TreeSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tizzi
 */
public class MenuPrincipal extends javax.swing.JFrame {
    public static TreeSet<Producto> listaProductos = new TreeSet<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        cargarProductos();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        jItemGestionProd = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jitemXnombre = new javax.swing.JMenuItem();
        jItemXprecio = new javax.swing.JMenuItem();
        jItemXrubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("De todo S.A.");

        escritorio.setPreferredSize(new java.awt.Dimension(400, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jmAdministracion.setText("Administracion");

        jItemGestionProd.setText("Gestion de Productos");
        jItemGestionProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemGestionProdActionPerformed(evt);
            }
        });
        jmAdministracion.add(jItemGestionProd);

        jMenuBar1.add(jmAdministracion);

        jmConsultas.setText("Consultas");

        jitemXnombre.setText("Consulta por Nombre");
        jitemXnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemXnombreActionPerformed(evt);
            }
        });
        jmConsultas.add(jitemXnombre);

        jItemXprecio.setText("Consulta por Precio");
        jItemXprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemXprecioActionPerformed(evt);
            }
        });
        jmConsultas.add(jItemXprecio);

        jItemXrubro.setText("Consulta por Rubro");
        jItemXrubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemXrubroActionPerformed(evt);
            }
        });
        jmConsultas.add(jItemXrubro);

        jMenuBar1.add(jmConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItemGestionProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemGestionProdActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestiondeProductos gp = new GestiondeProductos();
        gp.setVisible(true);
        escritorio.add(gp);
        escritorio.moveToFront(gp);
        
    }//GEN-LAST:event_jItemGestionProdActionPerformed

    private void jItemXrubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemXrubroActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConsultaPorRubro cpr = new ConsultaPorRubro();
        cpr.setVisible(true);
        escritorio.add(cpr);
        escritorio.moveToFront(cpr);
    }//GEN-LAST:event_jItemXrubroActionPerformed

    private void jitemXnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemXnombreActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConsultaPorNombre cpn = new ConsultaPorNombre();
        cpn.setVisible(true);
        escritorio.add(cpn);
        escritorio.moveToFront(cpn);
    }//GEN-LAST:event_jitemXnombreActionPerformed

    private void jItemXprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemXprecioActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConsultaPorPrecio cpp = new ConsultaPorPrecio();
        cpp.setVisible(true);
        escritorio.add(cpp);
        escritorio.moveToFront(cpp);
        
    }//GEN-LAST:event_jItemXprecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jItemGestionProd;
    private javax.swing.JMenuItem jItemXprecio;
    private javax.swing.JMenuItem jItemXrubro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jitemXnombre;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmConsultas;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos(){
        
    listaProductos.add(new Producto(15,"Galletas Oreo",4000.00,9,Categoria.COMESTIBLE));
    listaProductos.add(new Producto(10, "Azúcar 1kg", 1200.0, 50, Categoria.COMESTIBLE));
    listaProductos.add(new Producto(25, "Jabón Líquido", 3500.5, 20, Categoria.LIMPIEZA));
    listaProductos.add(new Producto(30, "Perfume Paco Rabanne", 8599.75, 12, Categoria.PERFUMERIA));
    
    }
}
